// <auto-generated-enum-options>
// Generated by: php artisan enums:sync

export type EnumOption<T extends string | number = string> = {
  label: string;
  value: T;
};

export const bloodTypeOptions = Object.freeze([
  { label: 'A Rh+', value: 'A+' },
  { label: 'A Rh-', value: 'A-' },
  { label: 'B Rh+', value: 'B+' },
  { label: 'B Rh-', value: 'B-' },
  { label: 'AB Rh+', value: 'AB+' },
  { label: 'AB Rh-', value: 'AB-' },
  { label: 'O Rh+', value: 'O+' },
  { label: 'O Rh-', value: 'O-' },
] as const);

export const getBloodTypeOptions = () => bloodTypeOptions;
export type BloodTypeValue = (typeof bloodTypeOptions)[number]['value'];

export const BloodType = Object.freeze({
  A_POSITIVE: 'A+',
  A_NEGATIVE: 'A-',
  B_POSITIVE: 'B+',
  B_NEGATIVE: 'B-',
  AB_POSITIVE: 'AB+',
  AB_NEGATIVE: 'AB-',
  O_POSITIVE: 'O+',
  O_NEGATIVE: 'O-',
} as const) satisfies Record<string, BloodTypeValue>;

export const genderOptions = Object.freeze([
  { label: 'Erkek', value: 'male' },
  { label: 'Kadın', value: 'female' },
] as const);

export const getGenderOptions = () => genderOptions;
export type GenderValue = (typeof genderOptions)[number]['value'];

export const Gender = Object.freeze({
  MALE: 'male',
  FEMALE: 'female',
} as const) satisfies Record<string, GenderValue>;

export const maritalStatusOptions = Object.freeze([
  { label: 'Bekar', value: 'single' },
  { label: 'Evli', value: 'married' },
  { label: 'Boşanmış', value: 'divorced' },
] as const);

export const getMaritalStatusOptions = () => maritalStatusOptions;
export type MaritalStatusValue = (typeof maritalStatusOptions)[number]['value'];

export const MaritalStatus = Object.freeze({
  SINGLE: 'single',
  MARRIED: 'married',
  DIVORCED: 'divorced',
} as const) satisfies Record<string, MaritalStatusValue>;

export const drivingLicenseClassOptions = Object.freeze([
  { label: 'B', value: 'B' },
  { label: 'BE', value: 'BE' },
  { label: 'C', value: 'C' },
  { label: 'CE', value: 'CE' },
  { label: 'D', value: 'D' },
  { label: 'DE', value: 'DE' },
  { label: 'F', value: 'F' },
] as const);

export const getDrivingLicenseClassOptions = () => drivingLicenseClassOptions;
export type DrivingLicenseClassValue = (typeof drivingLicenseClassOptions)[number]['value'];

export const DrivingLicenseClass = Object.freeze({
  B: 'B',
  BE: 'BE',
  C: 'C',
  CE: 'CE',
  D: 'D',
  DE: 'DE',
  F: 'F',
} as const) satisfies Record<string, DrivingLicenseClassValue>;

export const militaryServiceStatusOptions = Object.freeze([
  { label: 'Muaf', value: 'exempt' },
  { label: 'Yapıldı', value: 'completed' },
  { label: 'Tecilli', value: 'postponed' },
  { label: 'Başvuruya tabi değil', value: 'not_applicable' },
] as const);

export const getMilitaryServiceStatusOptions = () => militaryServiceStatusOptions;
export type MilitaryServiceStatusValue = (typeof militaryServiceStatusOptions)[number]['value'];

export const MilitaryServiceStatus = Object.freeze({
  EXEMPT: 'exempt',
  COMPLETED: 'completed',
  POSTPONED: 'postponed',
  NOT_APPLICABLE: 'not_applicable',
} as const) satisfies Record<string, MilitaryServiceStatusValue>;

export const uniformSizeOptions = Object.freeze([
  { label: 'XS', value: 'XS' },
  { label: 'S', value: 'S' },
  { label: 'M', value: 'M' },
  { label: 'L', value: 'L' },
  { label: 'XL', value: 'XL' },
  { label: 'XXL', value: 'XXL' },
  { label: '3XL', value: '3XL' },
] as const);

export const getUniformSizeOptions = () => uniformSizeOptions;
export type UniformSizeValue = (typeof uniformSizeOptions)[number]['value'];

export const UniformSize = Object.freeze({
  XS: 'XS',
  S: 'S',
  M: 'M',
  L: 'L',
  XL: 'XL',
  XXL: 'XXL',
  XXXL: '3XL',
} as const) satisfies Record<string, UniformSizeValue>;

export const attendanceLogDirectionOptions = Object.freeze([
  { label: 'Giriş', value: 'in' },
  { label: 'Çıkış', value: 'out' },
] as const);

export const getAttendanceLogDirectionOptions = () => attendanceLogDirectionOptions;
export type AttendanceLogDirectionValue = (typeof attendanceLogDirectionOptions)[number]['value'];

export const AttendanceLogDirection = Object.freeze({
  IN: 'in',
  OUT: 'out',
} as const) satisfies Record<string, AttendanceLogDirectionValue>;

export const attendanceLogSourceOptions = Object.freeze([
  { label: 'NFC', value: 'nfc' },
  { label: 'Otomatik Gün Sonu', value: 'auto_day_close' },
  { label: 'Manuel', value: 'manual' },
] as const);

export const getAttendanceLogSourceOptions = () => attendanceLogSourceOptions;
export type AttendanceLogSourceValue = (typeof attendanceLogSourceOptions)[number]['value'];

export const AttendanceLogSource = Object.freeze({
  NFC: 'nfc',
  AUTO_DAY_CLOSE: 'auto_day_close',
  MANUAL: 'manual',
} as const) satisfies Record<string, AttendanceLogSourceValue>;

export const workCalendarDayTypeOptions = Object.freeze([
  { label: 'Tatil', value: 'holiday' },
  { label: 'Şirket Etkinliği', value: 'company_event' },
  { label: 'Diğer', value: 'other' },
] as const);

export const getWorkCalendarDayTypeOptions = () => workCalendarDayTypeOptions;
export type WorkCalendarDayTypeValue = (typeof workCalendarDayTypeOptions)[number]['value'];

export const WorkCalendarDayType = Object.freeze({
  HOLIDAY: 'holiday',
  COMPANY_EVENT: 'company_event',
  OTHER: 'other',
} as const) satisfies Record<string, WorkCalendarDayTypeValue>;

export const workCalendarOffDurationOptions = Object.freeze([
  { label: 'Tam Gün Tatil', value: 'full_day_off' },
  { label: 'Yarım Gün Tatil', value: 'half_day_off' },
] as const);

export const getWorkCalendarOffDurationOptions = () => workCalendarOffDurationOptions;
export type WorkCalendarOffDurationValue = (typeof workCalendarOffDurationOptions)[number]['value'];

export const WorkCalendarOffDuration = Object.freeze({
  FULL_DAY_OFF: 'full_day_off',
  HALF_DAY_OFF: 'half_day_off',
} as const) satisfies Record<string, WorkCalendarOffDurationValue>;

export const workCalendarHalfDayPeriodOptions = Object.freeze([
  { label: 'Sabah', value: 'morning' },
  { label: 'Öğleden Sonra', value: 'afternoon' },
] as const);

export const getWorkCalendarHalfDayPeriodOptions = () => workCalendarHalfDayPeriodOptions;
export type WorkCalendarHalfDayPeriodValue = (typeof workCalendarHalfDayPeriodOptions)[number]['value'];

export const WorkCalendarHalfDayPeriod = Object.freeze({
  MORNING: 'morning',
  AFTERNOON: 'afternoon',
} as const) satisfies Record<string, WorkCalendarHalfDayPeriodValue>;

export const shiftSetWeekdayOptions = Object.freeze([
  { label: 'Pazartesi', value: 1 },
  { label: 'Salı', value: 2 },
  { label: 'Çarşamba', value: 3 },
  { label: 'Perşembe', value: 4 },
  { label: 'Cuma', value: 5 },
  { label: 'Cumartesi', value: 6 },
  { label: 'Pazar', value: 7 },
] as const);

export const getWeekdayOptions = () => shiftSetWeekdayOptions;
export type WeekdayValue = (typeof shiftSetWeekdayOptions)[number]['value'];

export const Weekday = Object.freeze({
  MONDAY: 1,
  TUESDAY: 2,
  WEDNESDAY: 3,
  THURSDAY: 4,
  FRIDAY: 5,
  SATURDAY: 6,
  SUNDAY: 7,
} as const) satisfies Record<string, WeekdayValue>;

export const statusOptions = Object.freeze([
  { label: 'Aktif', value: 1 },
  { label: 'Pasif', value: 0 },
] as const);

export const getStatusOptions = () => statusOptions;
export type StatusValue = (typeof statusOptions)[number]['value'];

export const Status = Object.freeze({
  ACTIVE: 1,
  INACTIVE: 0,
} as const) satisfies Record<string, StatusValue>;

export const tfaOptions = Object.freeze([
  { label: 'Açık', value: 1 },
  { label: 'Kapalı', value: 0 },
] as const);

export const getTFAOptions = () => tfaOptions;
export type TFAValue = (typeof tfaOptions)[number]['value'];

export const TFA = Object.freeze({
  ENABLED: 1,
  DISABLED: 0,
} as const) satisfies Record<string, TFAValue>;

export const taskPriorityOptions = Object.freeze([
  { label: 'Düşük', value: 'low' },
  { label: 'Orta', value: 'medium' },
  { label: 'Yüksek', value: 'high' },
  { label: 'Acil', value: 'urgent' },
] as const);

export const getTaskPriorityOptions = () => taskPriorityOptions;
export type TaskPriorityValue = (typeof taskPriorityOptions)[number]['value'];

export const TaskPriority = Object.freeze({
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  URGENT: 'urgent',
} as const) satisfies Record<string, TaskPriorityValue>;

export const taskStatusOptions = Object.freeze([
  { label: 'Beklemede', value: 'pending' },
  { label: 'Devam Ediyor', value: 'in_progress' },
  { label: 'Tamamlandı', value: 'completed' },
  { label: 'İptal Edildi', value: 'cancelled' },
] as const);

export const getTaskStatusOptions = () => taskStatusOptions;
export type TaskStatusValue = (typeof taskStatusOptions)[number]['value'];

export const TaskStatus = Object.freeze({
  PENDING: 'pending',
  IN_PROGRESS: 'in_progress',
  COMPLETED: 'completed',
  CANCELLED: 'cancelled',
} as const) satisfies Record<string, TaskStatusValue>;

export const taskRequestTypeOptions = Object.freeze([
  { label: 'Tamamlama Talebi', value: 'completion' },
  { label: 'Üstlenme Talebi', value: 'claim' },
] as const);

export const getTaskRequestTypeOptions = () => taskRequestTypeOptions;
export type TaskRequestTypeValue = (typeof taskRequestTypeOptions)[number]['value'];

export const TaskRequestType = Object.freeze({
  COMPLETION: 'completion',
  CLAIM: 'claim',
} as const) satisfies Record<string, TaskRequestTypeValue>;

export const taskRequestStatusOptions = Object.freeze([
  { label: 'Beklemede', value: 'pending' },
  { label: 'Onaylandı', value: 'confirmed' },
  { label: 'Reddedildi', value: 'rejected' },
] as const);

export const getTaskRequestStatusOptions = () => taskRequestStatusOptions;
export type TaskRequestStatusValue = (typeof taskRequestStatusOptions)[number]['value'];

export const TaskRequestStatus = Object.freeze({
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  REJECTED: 'rejected',
} as const) satisfies Record<string, TaskRequestStatusValue>;

export const assetCategoryTypeOptions = Object.freeze([
  { label: 'Elektronik', value: 'electronic' },
  { label: 'Giyim', value: 'clothing' },
  { label: 'Ayakkabı', value: 'footwear' },
  { label: 'Mobilya', value: 'furniture' },
  { label: 'Araç Gereç', value: 'tool' },
  { label: 'Sarf Malzeme', value: 'consumable' },
  { label: 'Diğer', value: 'other' },
] as const);

export const getAssetCategoryTypeOptions = () => assetCategoryTypeOptions;
export type AssetCategoryTypeValue = (typeof assetCategoryTypeOptions)[number]['value'];

export const AssetCategoryType = Object.freeze({
  ELECTRONIC: 'electronic',
  CLOTHING: 'clothing',
  FOOTWEAR: 'footwear',
  FURNITURE: 'furniture',
  TOOL: 'tool',
  CONSUMABLE: 'consumable',
  OTHER: 'other',
} as const) satisfies Record<string, AssetCategoryTypeValue>;

export const assetStatusOptions = Object.freeze([
  { label: 'Aktif', value: 'active' },
  { label: 'Pasif', value: 'inactive' },
  { label: 'Arşivlendi', value: 'archived' },
] as const);

export const getAssetStatusOptions = () => assetStatusOptions;
export type AssetStatusValue = (typeof assetStatusOptions)[number]['value'];

export const AssetStatus = Object.freeze({
  ACTIVE: 'active',
  INACTIVE: 'inactive',
  ARCHIVED: 'archived',
} as const) satisfies Record<string, AssetStatusValue>;

export const assetAssignmentStatusOptions = Object.freeze([
  { label: 'Zimmetli', value: 'assigned' },
  { label: 'İade Edildi', value: 'returned' },
  { label: 'Kayıp', value: 'lost' },
  { label: 'İptal Edildi', value: 'cancelled' },
] as const);

export const getAssetAssignmentStatusOptions = () => assetAssignmentStatusOptions;
export type AssetAssignmentStatusValue = (typeof assetAssignmentStatusOptions)[number]['value'];

export const AssetAssignmentStatus = Object.freeze({
  ASSIGNED: 'assigned',
  RETURNED: 'returned',
  LOST: 'lost',
  CANCELLED: 'cancelled',
} as const) satisfies Record<string, AssetAssignmentStatusValue>;

export const userDetailMediaCollectionOptions = Object.freeze([
  { label: 'Kimlik Belgeleri', value: 'identity-documents' },
  { label: 'Sözleşmeler', value: 'contracts' },
  { label: 'Sertifikalar', value: 'certificates' },
  { label: 'Diğer', value: 'other' },
] as const);

export const getUserDetailMediaCollectionOptions = () => userDetailMediaCollectionOptions;
export type UserDetailMediaCollectionValue = (typeof userDetailMediaCollectionOptions)[number]['value'];

export const UserDetailMediaCollection = Object.freeze({
  IDENTITY_DOCUMENTS: 'identity-documents',
  CONTRACTS: 'contracts',
  CERTIFICATES: 'certificates',
  OTHER: 'other',
} as const) satisfies Record<string, UserDetailMediaCollectionValue>;

// </auto-generated-enum-options>
